apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lvm.fullname" . }}
  labels:
    {{- include "lvm.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "lvm.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lvm.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "lvm.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "lvm.fullname" . }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  - storageclasses
  - volumeattachments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  - nodes
  - events
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  - secrets
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  - volumesnapshotcontents
  - volumesnapshots
  - volumesnapshots/status
  - volumesnapshotcontents/status
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - create