apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  ruleNamespaceSelector: {}
  retention: {{ .Values.retention }}
  alerting:
    alertmanagers:
    - name: alertmanager
      namespace: monitoring
      port: web
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: {{ .Values.storage.storageClass }}
        resources:
          requests:
            storage: {{ .Values.storage.size.prometheus }}
  baseImage: {{ .Values.image.prometheus.repository }}
  podMonitorSelector: {}
  replicas: {{ .Values.replicas.prometheus }}
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  additionalScrapeConfigs:
    name: additional-configs
    key: prometheus-additional.yaml
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: {{ .Values.image.prometheus.tag }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  affinity:
    {{- if eq .Values.podAntiAffinity "hard"}}
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: prometheus
                operator: In
                values:
                  - k8s
          topologyKey: {{ .Values.podAntiAffinityTopologKey }}
    {{- else if eq .Values.podAntiAffinity "soft"}}
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: {{ .Values.podAntiAffinityTopologKey }}
            labelSelector:
              matchExpressions:
                - key: prometheus
                  operator: In
                  values:
                    - k8s
    {{- end}}
    {{- with .Values.nodeAffinity }}
    nodeAffinity:
      {{- toYaml . | nindent 6 }}
    {{- end }}

