apiVersion: es.middleware.hc.cn/v1alpha1
kind: ESCluster
metadata:
  annotations:
    OperationType: Create
    developerPass: es
  name: {{ include "elasticsearch.fullname" . }}
spec:
  clusterMode: {{ .Values.cluster.mode }}
{{- if not .Values.clusterName }}
  clusterName: {{ include "elasticsearch.fullname" . }}
{{- else }}
  clusterName: {{ .Values.clusterName }}
{{- end }}
  checkHealthConfigMap: {{ include "elasticsearch.fullname" . }}-checkhealth-config
  elasticKibanaConfigMap: {{ include "elasticsearch.fullname" . }}-kibana-config
  elasticSearchConfigMap: {{ include "elasticsearch.fullname" . }}-es-config
  esExporterPort: 19114
  esHttpPort: 9200
  esKibanaPort: 5200
  esTcpPort: 9300
  elasticPass: {{ .Values.elasticPassword | quote}}
  {{- if .Values.kibanaPassword }}
  kibanaPass: {{ .Values.kibanaPassword }}
  {{- end}}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if eq .Values.version "6.8" }}
  kibanaImage: {{ .Values.image.repository }}/kibana:{{ .Values.image.kibanaImageTag }}
{{- else }}
  kibanaImage: {{ .Values.image.repository }}/kibana:{{ .Values.image.kibanaImageTag_7 }}
{{- end }}
  elasticBusyImage: {{ .Values.image.repository }}/busybox:{{ .Values.image.busyImageTag }}
  masterReplaces: {{ .Values.cluster.masterReplacesCount }}
  dataReplaces: {{ .Values.cluster.dataReplacesCount }}
  clientReplaces: {{ .Values.cluster.clientReplacesCount }}
  coldReplaces: {{ .Values.cluster.coldReplacesCount }}
  totalReplaces: {{ add .Values.cluster.masterReplacesCount .Values.cluster.dataReplacesCount .Values.cluster.clientReplacesCount .Values.cluster.coldReplacesCount  }}
  pod:
  - env:
  {{- if ((((.Values.logging).collection).stdout).enabled)}}
    - name: aliyun_logs_middlewarestdout
      value: stdout
    - name: aliyun_logs_middlewarestdout_tags
      value: middleware_name={{ include "elasticsearch.fullname" . }}
  {{- end}}
  {{- if ((((.Values.logging).collection).filelog).enabled)}}
    - name: aliyun_logs_middlewarelogstash
      value: /data/elastic/{{ include "elasticsearch.fullname" . }}/**/log/*.log
    - name: aliyun_logs_middlewarelogstash_tags
      value: middleware_name={{ include "elasticsearch.fullname" . }}
  {{- end}}
    - name: PathRepo
      value: {{ .Values.args.path_repo | default "/data/elastic/{ClusterName}/{PodName}/data/data_back" }}
    initImage: {{ .Values.image.repository }}/es-init:{{ .Values.image.initImageTag }}
    podAntiAffinityTopologKey: {{ .Values.podAntiAffinityTopologKey }}
    podAntiAffinity: {{ .Values.podAntiAffinity }}
    affinity:
    {{- with .Values.nodeAffinity }}
      nodeAffinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.storage }}
    storage:
    {{- toYaml .| nindent 6 }}
    {{- end }}
    {{- with .Values.esJavaOpts }}
    jvm:
    {{- toYaml .| nindent 6 }}
    {{- end }}
	{{- with .Values.extraVolumeMounts }}
    extraVolumeMounts:
    {{- toYaml .| nindent 6 }}
    {{- end }}
  {{- if eq .Values.version "6.8" }}
    middlewareImage: {{ .Values.image.repository }}/elastic:{{ .Values.image.elasticImageTag }}
  {{- else }}
    middlewareImage: {{ .Values.image.repository }}/elastic:{{ .Values.image.elasticImageTag_7 }}
  {{- end }}
    monitorImage: {{ .Values.image.repository }}/es-exporter:{{ .Values.image.exporterImageTag }}
    hostNetwork: {{ default false .Values.hostNetwork }}
    resources:
      {{- toYaml .Values.resources | nindent 6 }}
    updateStrategy: {}
  projectId: a9927d1581674f27
  repository: {{ .Values.image.repository }}
  type: {{ .Values.cluster.mode }}
  updateStrategy: {}
{{- if eq .Values.version "6.8" }}
  version: "6.8"
{{- else }}
  version: "7.16"
{{- end }}
  statefulset:
    spec:
      updateStrategy:
        type: RollingUpdate
      template:
        metadata:
          {{- with .Values.annotations }}
          annotations:
          {{- toYaml . | nindent 13 }}
          {{- end }}
          {{- with .Values.labels }}
          labels:
          {{- toYaml . | nindent 13 }}
          {{- end }}
        spec:
        {{- with .Values.statefulSetConfiguration }}
        {{- toYaml . | nindent 11 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
        {{- toYaml . | nindent 13 }}
        {{- end }}
  deploymentComponent:
    kibana:
      spec:
        template:
          metadata:
            {{- with .Values.annotations }}
            annotations:
            {{- toYaml . | nindent 15 }}
            {{- end }}
            {{- with .Values.labels }}
            labels:
            {{- toYaml . | nindent 15 }}
            {{- end }}
          spec:
          {{- with .Values.deploymentConfiguration }}
          {{- toYaml . | nindent 13 }}
          {{- end }}
          {{- with .Values.tolerations }}
            tolerations:
          {{- toYaml . | nindent 15 }}
          {{- end }}
    exporter:
      spec:
        template:
          metadata:
            {{- with .Values.annotations }}
            annotations:
            {{- toYaml . | nindent 15 }}
            {{- end }}
            {{- with .Values.labels }}
            labels:
            {{- toYaml . | nindent 15 }}
            {{- end }}
          spec:
          {{- with .Values.deploymentConfiguration }}
          {{- toYaml . | nindent 13 }}
          {{- end }}
          {{- with .Values.tolerations }}
            tolerations:
          {{- toYaml . | nindent 15 }}
          {{- end }}
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: es-data
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: {{ .Values.storageSize }}
      {{- if .Values.storageClassName }}
      storageClassName: {{ .Values.storageClassName }}
      {{- end}}
    status: {}
  volumes: {}
  {{- with .Values.extraVolumes }}
  extraVolumes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
