apiVersion: v1
kind: Service
metadata:
  name: {{ include "fs-exporter.fullname" . }}
  labels:
    {{- include "fs-exporter.labels" . | nindent 4 }}
spec:
  {{- if .Values.hostNetWork }}
  clusterIP: None
  {{- end }}
  selector:
    app: fs-exporter
    {{- include "fs-exporter.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.web.port }}
    targetPort: {{ .Values.web.port }}
    protocol: TCP
    name: fs-exporter
  type: ClusterIP
