apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: zeus-mysql
  name: zeus-mysql
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeus-mysql
  serviceName: zeus-mysql
  template:
    metadata:
      labels:
        app: zeus-mysql
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - zeus-mysql
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: ZeuS@Middleware01
          image: "{{ .Values.global.repository }}/{{ .Values.global.zeus_mysql.image }}:{{ .Values.global.zeus_mysql.tag }}"
          imagePullPolicy: {{ .Values.global.zeus_mysql.pullPolicy }}
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          resources:
            {{- toYaml .Values.global.zeus.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data/mysql/db_zeus-mysql
              name: mysql-data
            - mountPath: /docker-entrypoint-initdb.d/
              name: zeus-mysql-init-sql-file
      dnsPolicy: ClusterFirst
      volumes:
        - configMap:
            defaultMode: 420
            name: zeus-mysql-init-sql-file
          name: zeus-mysql-init-sql-file
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5G
        storageClassName: {{ .Values.global.storageClass }}
        volumeMode: Filesystem