---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstash.fullname" . }}-config
  labels:
    app: "{{ template "logstash.fullname" . }}"
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    {{- include "logstash.labels" . | nindent 4 }}
data:
  logstash.yml: |
    pipeline.workers: {{ .Values.args.pipelineWorker }}
    pipeline.output.workers: {{ .Values.args.pipelineOutputWorker }}
    pipeline.batch.size: {{ .Values.args.pipelineBatchSize }}
    pipeline.batch.delay: {{ .Values.args.pipelineBatchDelay }}
    http.host: 0.0.0.0
