apiVersion: v1
data:
  config.yml: |-
    logstash:
      servers:
        - url: "http://{{ include "logstash.fullname" . }}-headless:9600"
    server:
      host: "0.0.0.0" 
      port: 9198 
    logging:
      level: "info"

kind: ConfigMap
metadata:
  name: {{ include "logstash.fullname" . }}-exporter-config