parameters:
  - pipelineWorker:
      - name: default
        value: 3
      - name: isReboot
        value: y
      - name: range
        value: [int]
      - name: describe
        value: "管道中处理事件的线程数量，通常是当前系统的 CPU 核心数"
  - pipelineOutputWorker:
      - name: default
        value: 2
      - name: isReboot
        value: y
      - name: range
        value: [int]
      - name: describe
        value: "设置用于输出事件的线程数"
  - pipelineBatchSize:
      - name: default
        value: 256
      - name: isReboot
        value: y
      - name: range
        value: [int]
      - name: describe
        value: "控制每个批次中处理的事件数量"
  - pipelineBatchDelay:
      - name: default
        value: 3000
      - name: isReboot
        value: y
      - name: range
        value: [int]
      - name: describe
        value: "Logstash 在形成一个批次之前的最大等待时间"
