global:
  repository: harbor.middleware.com/middleware
  crdGroup: harmonycloud
  middleware_controller:
    controller:
      pvTopology: false
      gracefulRestart: true
    image: middleware-controller
    tag: v1.2.19
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 512Mi
    nodeSelector: {}
  kubectl:
    installCRDs: true
    tag: 1.21
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
  middleware_api:
    image: middleware-api
    tag: v0.1.0
    pullPolicy: Always
    replicaCount: 1
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    serviceAccount:
      create: true
      annotations: {}
      name: ""
    service:
      type: ClusterIP
      port: 8080
    nodeSelector: {}

podAntiAffinityTopologKey: "kubernetes.io/hostname"

#取值[hard|soft] hard:强制反亲和 soft:非强制反亲和
podAntiAffinity: "soft"
