nodeSelector:
  system: "true"

# Tolerations to use for the lvm-provisioner deployment. Optional.
tolerations:
  - effect: NoSchedule
    key: harm.cn/type
    value: active-active
  - effect: NoSchedule
    key: harm.cn/system

storage:
  default: true
  vgName: logvg02
  storageClassName: middleware-lvm
  size: 100