image:
  repository: 10.120.1.233:8443/k8s-deploy
  pullPolicy: IfNotPresent
  registrarImageTag: v2.8.0
  pluginImageTag: v1.2.4
  provisionerImageTag: v3.0.0-fa5f64b-ack
  resizerImageTag: v1.7.0
  snapshotControllerImageTag: v4.2.0
  csiSnapshotterImageTag: v4.2.0

provisioner:
  replicas: 1
  provisioner:
    resources:
      limits:
        memory: 512Mi
        cpu: 200m
      requests:
        memory: 256Mi
        cpu: 100m
  resizer:
    resources:
      limits:
        memory: 256Mi
        cpu: 100m
      requests:
        memory: 256Mi
        cpu: 100m

plugin:
  plugin:
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
  registrar:
    resources:
      requests:
        memory: 128Mi
        cpu: 50m

nodeSelector:
  beta.kubernetes.io/os: linux

tolerations:
  - operator: Exists

storage:
  default: true
  vgName: vg_middleware
  storageClassName: middleware-lvm
  size: 100

volumeSnapshotClass:
  type: minio
  # minio
  userId: bWluaW8=
  # minio123
  userKey: bWluaW8xMjM=
  # 123456
  backupPassword: MTIzNDU2Cg==
  bucket: restic-bucket
  url: http://minio-cluster-svc.minio.svc.cluster.local:9000