apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    platform: zeus
    role: alert-rules
  annotations:
    target_type: cluster
    target_alias_name: "Local-Path控制器"
    target_name: localPathController
  name: local-path-rules
spec:
  groups:
  - name: middleware-rules
    rules:
    - alert: localPathCpuUsageHigh
      annotations:
        message: cpu usage high for {{`{{ $labels.pod }}`}}
        summary: cpu usage high for {{`{{ $labels.pod }}`}}
      expr: (sum by (pod) (rate(container_cpu_usage_seconds_total{image!="",container!~"|POD",endpoint!="", pod=~"local-path-.+",namespace="middleware-operator"}[5m]))) / (sum by (pod) (kube_pod_container_resource_requests{resource="cpu", pod=~"local-path-.+", namespace="middleware-operator"})) > 0.8
      for: 5m
      labels:
        severity: critical
    - alert: localPathMemoryUsageHigh
      annotations:
        message: memory usage high for {{`{{ $labels.pod }}`}}
        summary: memory usage high for {{`{{ $labels.pod }}`}}
      expr: (sum by (pod)(container_memory_working_set_bytes{container!~"|POD",endpoint!="",pod=~"local-path-.+",namespace="middleware-operator"})) * 100 / (sum by (pod) (kube_pod_container_resource_requests{resource="memory",pod=~"local-path-.+",namespace="middleware-operator"})) > 80
      for: 5m
      labels:
        severity: critical
    - alert: localPathInstanceNotReady
      annotations:
        message: localPath instance {{`{{ $labels.instance }}`}} not ready
        summary: localPath instance {{`{{ $labels.instance }}`}} not ready
      expr: kube_pod_container_status_ready{namespace="middleware-operator",container=~"local-path-provisioner",pod=~"local-path-.+"} == 0
      for: 30s
      labels:
        severity: warning
    - alert: localPathInstanceNotRunning
      annotations:
        message: localPath instance {{`{{ $labels.instance }}`}} not running
        summary: localPath instance {{`{{ $labels.instance }}`}} not running
      expr: kube_pod_container_status_running{namespace="middleware-operator",container=~"local-path-provisioner",pod=~"local-path-.+"} == 0
      for: 30s
      labels:
        severity: critical
