{{ if .Values.storageClass.create -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
{{ include "local-path-provisioner.labels" . | indent 4 }}
{{- if .Values.storageClass.defaultClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: {{ template "local-path-provisioner.provisionerName" . }}
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
allowVolumeExpansion: true
parameters:
  {{- if .Values.mode }}
  mode: {{ .Values.mode }}
  {{- end }}
{{- if .Values.scheduleNodes }}
allowedTopologies:
  - matchLabelExpressions:
      - key: kubernetes.io/hostname
        values:
{{- toYaml .Values.scheduleNodes | nindent 10}}
{{- end }}
{{- end }}
