apiVersion: v2
appVersion: 1.3.0
description: Universal mounted-pv storage usage monitoring
maintainers:
- email: zhangyiyan@harmonycloud.cn
  name: zhangyiyan
name: fs-exporter
type: application
version: 1.3.0
