# command line parameters
web:
  listenAddress: "0.0.0.0:9100"
  port: 9100
logLevel: 4 # Info Level

image:
  registry: "" # 10.10.102.124/middleware/
  repository: fs-exporter
  tag: "v1.5.1" # Overrides the image tag whose default is the chart appVersion.
  pullPolicy: IfNotPresent

hostNetWork: false

resources:
  limits:
    cpu: 250m
    memory: 180Mi
  requests:
    cpu: 100m
    memory: 180Mi

nodeSelector: {}
tolerations:
  - operator: Exists
affinity: {}
podAnnotations: {}
# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""
# podSecurityContext: {}
# securityContext: {}
