# command line parameters
web:
  listenAddress: "127.0.0.1:9100"
  port: 9100
logLevel: 4 # Info Level

image:
  registry: "10.120.1.233:8443/zyydebug/"
  repository: fs-exporter
  tag: "1.1.0" # Overrides the image tag whose default is the chart appVersion.
  pullPolicy: IfNotPresent

hostNetWork: false

resources:
  limits:
    cpu: 250m
    memory: 180Mi
  requests:
    cpu: 100m
    memory: 180Mi

nodeSelector: {}
tolerations:
  - operator: Exists
affinity: {}
# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""
# podAnnotations: {}
# podSecurityContext: {}
# securityContext: {}
