name: "pgsql优雅重启"
jobs:
  - name: "初始化状态检查"
    cmd: "kubectl -n $namespace get $kind $name -o json |jq -r '.status.phase'"
    result: "Running"
  - name: "记录当前主从状态"
    func: SavePodType
  - name: "重启异步同步节点"
    func: DeletePod
    para:
      type: "slave|sync_slave"
      limit: "1"
  - name: "等待集群正常"
    func: WaitReady
  - name: "记录当前主从状态"
    func: SavePodType
  - name: "主从切换"
    para:
      cmd: "port=$(kubectl -n $namespace get svc $name-patroni -o json|jq '.spec.ports[0].port' -r) && echo $port &&  kubectl -n $namespace exec  $podName -c postgres  -- curl -X POST http://$name-patroni:$port/failover -d \"{\\\"candidate\\\": \\\"$podName\\\"}\""
      type: sync_slave
      limit: "1"
    func: SwitchOver
  - name: "等待集群正常"
    func: WaitReady
  - name: "重启剩余节点"
    func: DeletePod
  - name: "重启完毕，等待状态恢复正常"
    func: WaitReady