100001=System error, please contact Administrator.
100002=Invalid parameter.
100003=Validate failed.
100004=Fail to create the temporary file
100005=Target file not found
100006=I/O failed
100007=Auth failed
100008=yaml format incorrect.
100009=failed to parse object to configmap
100010=Auth failed
100011=Parameter is not complete
100012=Query failed.
100013=does not exist
100014=Create fail.
100015=Update fail.
100016=Can not be blank.
100017=Cmd run failed
100018=Switch fail.
100019=Existing.
100020=failed to update configmap
100021=not exist or not running
100022=list backup failed
100023=create backuop failed
100024=delete backup failed
100025=backup file not exist
100026=delete backup failed
100027=Time pick error, please try again
100028=middleware backup update failed
100029=increment middleware backup schedule error
100030=sync_slave not found
100031=find backup schedule cron failed
100032=Date error, start date is after end date.
100033=resource metadata not found
100034=resource kind not found
100035=resource name not found
100036=resource namespace not found
100037=not lvm
100038=failed to find pvc
100039=result is empty
100040=do not use chinese
100041=login caas api failed
100042=license check failed
100043=license used in platform
100044=license cpu resource not enough
100045=Access to external service failed
100046=no authority with external service
100047=backup server has bean bound
100048=switch to backup platform
100049=Illegal token
100050=Token has timed out
100051=Token not yet effective
100052=does not exist.
101012=Parameter cannot be null.
101013=Fail to delete some services.
101014=Delete failed.
101015=add fail.
101016=get fail.
101017=Not found.
200001=Registry not found.
200002=Cannot connect registry component.
200003=Auth string of project for registry cannot be null.
200004=Auth string for registry cannot be null.
200005=call registry api failed.
200006=Registry name duplicated.
200007=Registry nickname duplicated.
200008=Fail to create the Registry user.
200009=Repository not found.
200010=Retention rule policy is not support
200011=Retention timing cannot be set when retention rule is empty
200012=Target registry is unhealthy, please add after test connect successful.
200013=Registry user not found
200014=Registry url duplicated.
200015=The number of retention rule param is gather 1, not support.
200016=Current registry type or version cannot support this function
200017=It's not allowed to operate system repository
210001=Registry is not bind to the project
210002=Fail to unbind registry and project
210003=Project or role has no permission in this repo
211001=Fail to transfer the helm chart file
211002=Fail to unzip the helm chart file
211003=Fail to write the helm chart file
211004=Fail to read the chart yaml
211005=Helm chart format error
211006=helm install prometheus failed
211007=helm install local path failed
211008=helm install nginx ingress failed
211009=helm install alertmanager failed
211010=helm install middleware controller failed
211011=helm install minio frailed
211012=helm install log failed
211013=helm chart has been existed
211014=helm template not founf
211015=unsupported yaml of this type
220001=Cannot connect to dockerd
220002=Multi-image upload in one package not support
220003=Download image must before fetch
230001=Image not found
230002=Image tag not found
230003=Image tag already exists
230004=Sync image error. Same image name and tag exist in dest repository
230005=Sync image error. Fail to create the image replication policy
240001=The same name label is already existed
250001=The retention rule not exist
260001=Target registry is invalid, please check metadata
260002=Target registry not found
260003=Target registry is duplicate, please check name and url
300001=Cluster not found
300002=Auth string for cluster cannot be null
300003=Not support auth type
300004=Cannot connect cluster
300005=Call cluster api failed
300006=Resource already exist in cluster
300007=Cluster component address not found
300008=Cluster monitor info not found
300009=Cluster component is unsupported
300010=Cant not connect to es service.
300011=Please make sure ingress has deployed and tcp configmap is filed in before deploy this component.
300012=Namespace name can not be blank.
300013=no clusters have been registered
300014=cluster is not empty
300015=failed to registry namespace
300016=failed to find namespace
300017=prometheus has not been installed or integrated
300018=alertManager has not been installed or integrated
300019=namespace has existed
300020=ingress class has existed
300021=ingress class not existed
300022=LVM already existed
300023=local-path already exist
300024=failed to connect to elasticsearch
300025=delete namespace middleware-operator failed
300026=field can not be less than previous value
300027=namespace not empty
300028=alias name has existed
300029=storage class not found
300030=storage class name exist
300031=storage class is being used
300032=ingress class has existed
300033=cluster not add repository
300034=components not found
300035=ingress components values not found
300036=cluster not set default repository
300037=storage not enough
300038=update the maximum log retention time failed
300039=cluster id can't be empty
300040=configmap not exist
300041=search type not support.
300042=Pod not exist.
300044=deploy pod and container can not be blank at same.
300045=pod migrate failed
300046=sync_slave pod have data delay
300047=pod migrate info not exists
300048=The connection address for Prometheus is incorrect.
301001=Install package not found
301002=node not found
301003=node contains middleware pods
302001=Grafana login fail.
400001=user not exit.
400002=User has bound with role
400003=user has not bound with role,please contact administrator to bind role.
400004=role not exist
400005=username should not be null
400006=username has been used
400007=no authority
400008=wrong password
400009=the new password do not match repeat new password
400010=Decrypt password by private key failed
400011=failed to create role
400012=role name has been used
400013=failed to update role
400014=role has been bound
400015=role permission is empty
400016=role namespace perimission should not be empty
400017=Login failed
400018=password is expired.
400019=drop user failed
400020=connect to ldap server failed
400021=Incomplete parameters
400022=connect to smtp server failed
400023=Incomplete parameters
400024=invalid mail address
400025=connect to ding server failed
400026=Incomplete parameters
400027=webhook repetition
400028=ldap user not exist
400050=Incomplete parameters
400051=two password not match
400052=mysql update password failed
400053=mysql connection failed,please check service routine,Ensure that at least  one external service exposure is available
400101=Project not exist
400102=This namespace is already bound to a project
400103=project is not empty
400104=project name exist
400105=namespace is not empty
400106=The storage has assigned quotas to namespaces; please cancel the assignment first
400107=project cpu memory using
400108=project backup server using
400109=project add user list is empty
400150=organization not exist
400151=organization name has been existed
400152=organization user used in project
400153=organization include project
400154=organization storage using
400155=organization cpu memory using
400156=organization backup server using
400157=organization add user list is empty
400201=Incomplete parameters
400202=Temporary does not support cluster
400203=value is not an integer or out of range
400204=The key already exists
400205=redis server connection failed
400206=unselected database
400207=not an integer value
400208=find master node faild
500001=Cannot found useful port for nginx ingress controller https port
500002=Cannot found useful port for nginx ingress controller health port
500003=Cannot found useful port for nginx ingress controller status port
500004=Loadbalancer not exist
500005=Domain already exist
500006=Invalid CA file
600001=ingress not exist
600002=ingress name already exist
600003=Domain duplicate.
600005=external routing TCP port already exists
600006=the external routing TCP list cannot be empty
600007=the external routing TCP port cannot be empty
600008=the external routing TCP configuration does not exist
600009=unsupported method of external exposure
600010=the external routing NodPort list cannot be empty
600011=external routing NodePort port already exists
600012=the old external routing TCP port cannot be empty
600013=ingress domain name format not supported
600014=external routing port already used
600015=the ingress is not available
600016=the port is defined by traefik
600017=Unknown NodPort for external routing
650001=prometheus alert rule is not exist.
650002=Failed to update prometheus alert rules.
650003=Failed to create prometheus alert rules.
650004=Failed to delete prometheus alert rules.
650005=LOG_ALERT_NAME_EXISTS
650101=Bucket already exists
650102=connection failed
650103=chinese name repetition
660001=Failed to find grafana id
660002=grafana dashboard not found
700001=The restart pod is not assign to the middleware cluster, please refresh browser and try again.
700002=Please make sure this middleware cluster is Running.
700003=This middleware cluster pod role are error.
700004=middleware not exist
700005=the midllware cluster is in the abnormal state
700006=Middleware create success, but expose fail, please try again in the detail page
700007=Middleware backup storage is not exist.
700008=The number of Middleware reaches the limit. Please update the license.
700009=Upload failed!
700010=Failed to update custom config to mysql!
700011=Failed to create dynamic form!
700012=Failed to create middleware operator
700013=This version is being used by other cluster and cannot be taken down
700014=Exist released middleware service
700015=failed to fing cache middleware
700016=failed to restart middleware
700017=failed to find pod in middleware
700018=failed to parse values from string to JSONObject
700019=failed to set global for mysql
700020=failed to config set for redis
700021=custom config is empty
700022=custom config values is empty
700023=custom config template exist
700024=middleware controller component not install
700025=middleware controller component install failed
700026=same name middleware storage still exist
700027=crd not exist
700028=the component already exists
700029=middleware manager platform not support
700030=middleware pvc scale up failed
700031=middleware pvc roll back failed
700032=namespace quota not enough
700033=middleware maintenance scale up not found
700034=maintenance status error
700035=get custom config role failed
700036=custom config role can not be null
700037=update config config failed
700038=mongodb get organ Id failed
710000=Backup already exists
710001=Record delete failed,record may not exist
710002=backup restore failed
710003=The backup job name already exists
710004=create increment backup failed
710005=middleware backup schedule existed
710006=The max cron interval must small than retentionTime
710007=backup record not exists
710008=failed to delete backup restore
710009=There is an ongoing schedule backup task.
710010=Incremental backup not exist
720000=Can't upgrade to lower version
720001=Can't upgrade over big version
720002=Not satisfy lowest version
720003=Operator is updating
720004=Current operator version is too lower,please upgrade operator
720005=operator info error
730001=postgresql create database failed
730002=postgresql update database failed
730003=postgresql delete database failed
730004=postgresql create schema failed
730005=postgresql update schema failed
730006=postgresql delete schema failed
730007=postgresql create table failed
730008=postgresql update table failed
730009=postgresql delete table failed
730010=postgresql database not found
730011=postgresql schema not found
730012=postgresql table not found
730013=postgresql create foreign key failed
730014=postgresql create unique failed
730015=postgresql create exclusion failed
730016=postgresql create check failed
730017=postgresql drop constraint failed
730018=postgresql add table inherit failed
730019=postgresql drop table inherit failed
730020=postgresql create user failed
730021=postgresql delete user failed
730022=postgresql update user failed
730023=postgresql grant user database failed
730024=postgresql grant user schema failed
730025=postgresql grant user table failed
730026=postgresql revoke user database failed
730027=postgresql revoke user schema failed
730028=postgresql revoke user table failed
730029=postgresql select failed
730030=middleware manager center request error
730031=postgresql create table, column could not be null
730032=postgresql user reset password failed
730033=postgresql sync pod not exist
800000=failed to create database
800001=failed to delete database
800002=failed to update database
800003=database exists
800004=failed to exec query
740000=failed to save backup server detail
740001=This item has already created a backup location using this backup server, and cannot be created again
740002=can't found backup server
740003=the server name already exists
740004=the server address already exists
740005=authorization failed
740006=failed to delete this backup server,which a backup task used it already
740007=There are backup tasks that use this backup location, and it cannot be deleted
810001=failed to create user
810002=failed to create user
810003=user already exists
810004=db already exists
810005=login failed,wrong username or password
810006=user not exists
810007=failed to update user password
810008=failed to lock user
810009=failed to unlock user
810010=failed to grant database privilege
810011=failed to grant table privilege
810012=failed to revoke database privilege
810013=failed to revoke table privilege
810014=failed to update user
820000=failed to create table
820001=failed to delete table
820002=failed to update table
820003=failed to obtain table detail
820004=failed to export table sql
820005=failed to export table excel
820006=failed to obtain table data
820007=failed to obtain table recordd
820008=a table must have at least one column
820009=failed to update table columns
820010=failed to update table indices
820011=failed to update table foreign keys
860001=failed to login redis,maybe wrong username or password
860002=failed to query key info
860003=unknown redis cluster
860004=too long expire time
870001=error postgresql pod num
900001=relation service address not exist
900002=switch platform is not support
900003=please check your relation cluster is running or your connection address is right
900004=switch failed, please contact Administrator
900005=check whether the platform is connected to the primary platform
900006=the primary platform does not support the dissterRecovery
900007=the current platform is standby and only the super administrator can log in