apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: middlewarebackupresults.harmonycloud.cn
spec:
  conversion:
    strategy: None
  group: harmonycloud.cn
  names:
    kind: MiddlewareBackupResult
    listKind: MiddlewareBackupResultList
    plural: middlewarebackupresults
    singular: middlewarebackupresult
    shortNames:
      - mbr
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: MiddlewareBackup is the Schema for the middlewarebackups API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: MiddlewareBackupResultSpec defines the desired state of MiddlewareBackupResult
              properties:
                pod:
                  type: string
                pvc:
                  type: string
                snapshotResults:
                  items:
                    properties:
                      pod:
                        type: string
                      pvc:
                        type: string
                      backupId:
                        type: string
                      path:
                        type: string
                      repository:
                        type: string
                      size:
                        type: string
                      creationTimestamp:
                        format: date-time
                        type: string
                    type: object
                  type: array
                creationTimestamp:
                  format: date-time
                  type: string
                backupTimestamp:
                  type: string
                backupId:
                  type: string
                size:
                  type: string
                repository:
                  type: string
                backendStorage:
                  type: string
                esSnapshotInfo:
                  properties:
                    esClusterName:
                      type: string
                    bucketName:
                      type: string
                    snapshotRepository:
                      type: string
                    snapshotName:
                      type: string
                    indices:
                      type: string
                  type: object
                redisInfo:
                  properties:
                    operationType:
                      type: string
                    sourceClusterName:
                      type: string
                    sourceNamespace:
                      type: string
                    sourceType:
                      type: string
                  type: object
              type: object
            status:
              description: MiddlewareBackupResultStatus defines the observed state of MiddlewareBackupResult
              properties:
                creationTimestamp:
                  format: date-time
                  type: string
                phase:
                  type: string
                reason:
                  type: string
                storageProvider:
                  additionalProperties:
                    additionalProperties:
                      type: string
                    type: object
                  type: object
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: { }