imagePullSecrets:
  - name: registrysecret

tolerations:
  - operator: Exists

podAntiAffinityTopologKey: "zone"

#取值[hard|soft] hard:强制反亲和 soft:非强制反亲和
podAntiAffinity: "soft"

nodeAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
          - key: system
            operator: In
            values:
              - "true"
      weight: 100

