apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "log-pilot.fullname" . }}
  labels:
    k8s-app: log-pilot
    node-pool: ignore
spec:
  selector:
    matchLabels:
      k8s-app: log-pilot
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: log-pilot
        node-pool: ignore
    spec:
      tolerations:
      - operator: Exists
      containers:
      - name: log-pilot
        {{- if eq .Values.runtime.type "containerd"}}
        image: {{ .Values.image.repository }}/log-pilot:{{ .Values.runtime.imageContainerdTag | default .Chart.AppVersion }}
        {{- else }}
        image: {{ .Values.image.repository }}/log-pilot:{{ .Values.runtime.imageDockerTag | default .Chart.AppVersion }}
        {{- end}}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        {{- if eq .Values.logging_output.type "logstash"}}
        - name: "LOGGING_OUTPUT"
          value: "logstash"
        - name: "LOGSTASH_HOST"
          value: "{{ .Values.logging_output.address }}"
        - name: "LOGSTASH_PORT"
          value: "5044"
        - name: LOGSTASH_BULK_MAX_SIZE
          value: "3500"
        - name: "LOGSTASH_LOADBALANCE"
          value: "true"
        {{- end}}
        {{- if eq .Values.logging_output.type "kafka"}}
        - name: "LOGGING_OUTPUT"
          value: "kafka"
        - name: "KAFKA_BROKERS"
          value: "{{ .Values.logging_output.address }}"
        {{- end}}
        - name: "NODE_NAME"
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PILOT_LOG_PREFIX
          value: aliyun
        volumeMounts:
        {{- if eq .Values.runtime.type "containerd"}}
        - name: sock
          mountPath: /var/run/containerd/containerd.sock
        {{- else }}
        - name: sock
          mountPath: /var/run/docker.sock
        {{- end}}
        - name: logs
          mountPath: /var/log/filebeat
        - name: state
          mountPath: /var/lib/filebeat
        - name: root
          mountPath: /host
          mountPropagation: Bidirectional
          readOnly: true
        {{- if .Values.customVolumes }}
        - name: appl
          mountPath: {{ .Values.customVolumes.mountPath }}
          mountPropagation: Bidirectional
          readOnly: true
        {{- end}}
        - name: localtime
          mountPath: /etc/localtime
        - name: filebeat-config
          mountPath: /pilot/config.filebeat
          subPath: config.filebeat
        - mountPath: /pilot/filebeat.tpl
          name: filebeat-tpl
          subPath: filebeat.tpl
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
      terminationGracePeriodSeconds: 30
      hostNetwork: false
      serviceAccount: log-pilot
      volumes:
      {{- if eq .Values.runtime.type "containerd"}}
      - name: sock
        hostPath:
          path: /var/run/containerd/containerd.sock
      {{- else }}
      - name: sock
        hostPath:
          path: /var/run/docker.sock
      {{- end}}
      - name: logs
        hostPath:
          path: /var/log/filebeat
      - name: state
        hostPath:
          path: /var/lib/filebeat
      - name: root
        hostPath:
          path: /
      {{- if .Values.customVolumes }}
      - name: appl
        hostPath:
          path: {{ .Values.customVolumes.hostPath }}
      {{- end}}
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: filebeat-config
        configMap:
          defaultMode: 511
          name: {{ include "log-pilot.fullname" . }}-config
      - configMap:
          defaultMode: 511
          name: {{ include "log-pilot.fullname" . }}-tpl
        name: filebeat-tpl

