apiVersion: v1
kind: Service
metadata:
  name: caas-middleware-ui-svc
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - name: port-30088
    nodePort: {{ .Values.global.middleware_ui.nodePort }}
    port: 30088
    protocol: TCP
    targetPort: 30088
  - name: port-30043
    port: 30043
    protocol: TCP
    targetPort: 30043
  selector:
    app: caas-middleware-ui
  sessionAffinity: None
  type: NodePort
