apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: middleware-admission-webhook-cfg
  labels:
    app: middleware-admission-webhook
webhooks:
  - name: middleware-admission-webhook.hc.com
    admissionReviewVersions: ["v1"]
    failurePolicy: Ignore
    sideEffects: None
    clientConfig:
      service:
        name: middleware-admission-webhook-svc
        namespace: middleware-operator
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvakNDQW9xZ0F3SUJBZ0lVTHNHN2QvTFlZVlNWVElUcFFWY1dQU3RSVVNrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQWdUQms5eVpXZHZiakVSTUE4R0ExVUVCeE1JVUc5eQpkR3hoYm1ReEV6QVJCZ05WQkFvVENrdDFZbVZ5Ym1WMFpYTXhDekFKQmdOVkJBc1RBa05CTVJNd0VRWURWUVFECkV3cExkV0psY201bGRHVnpNQ0FYRFRJek1EVXhPREExTlRRd01Gb1lEekl4TWpNd05ESTBNRFUxTkRBd1dqQm8KTVFzd0NRWURWUVFHRXdKVlV6RVBNQTBHQTFVRUNCTUdUM0psWjI5dU1SRXdEd1lEVlFRSEV3aFFiM0owYkdGdQpaREVUTUJFR0ExVUVDaE1LUzNWaVpYSnVaWFJsY3pFTE1Ba0dBMVVFQ3hNQ1EwRXhFekFSQmdOVkJBTVRDa3QxClltVnlibVYwWlhNd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURYOGxUWDdqRXMKeXkwNTdrLzZOYmtvUHNjaWZGU2FERjZMdEhTemNBczVMeHhScTNES090dnB2aEJlMG5kSzN2a1dleXhlM24wOApMNE1ZcDFzSHQvY2hzK0JkdFJtUFBUTFB0TnhtOE1leVBsWUI3THBHTFlnRUJ5Y1lwNjVOZklHNmNveUI1MlhiClBTQ01mNllKaTFVbUM3ME50b0NhSzAyRENwejByQzgxM3RKL1FacDFvNnJUQWtpUWZ0Qy9sdVJyMW9HU0R5TTUKU1Jmc3I5aFdCZUNCMXJSNTNBTEE3Q21GZkRJK0tVaXBKYVNwcmt2NnhNWFh1Y0EyUTJCR0JudFdySHIxSGtWKwo1dXdoK08zSS9lLzB1Y3hUeUM3RkJzY3pvVzlZbG55Zk82RFdmTXJqeGxBYUNRYjRXN2lWNmpGaEsxdnpuMGxRCnRkZW9aa2lOZFhmaEFnTUJBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCQmpBUEJnTlZIUk1CQWY4RUJUQUQKQVFIL01CMEdBMVVkRGdRV0JCUnBXUlZ5eWY3ZzBwd1NGYVpTSEUrNG5QVnIxVEFOQmdrcWhraUc5dzBCQVFzRgpBQU9DQVFFQVd0RitDYkpLOU9xcDFRVXBmZHpqUTEwNVhUcHNRVTIrYjdPc3VId08vZVo3aW8vNW13ZTNYbVNmCnBDYjNXdTJ5U25tcktxVjVrc2Rob0NBWkYvR0lTb2ozczl4YTFLdEttRTMvbzhKSDNuTlVXclVyQTJjc1diNjIKckNjc3lIejRreGxRRWs0U3AxbW1pWStxNUJwTlAvZCtDOFF3b0VMUEZBRmNYcEJZek1nRjhmaVhwNkczTDlOYwpUQmZzZlFmczRsSG1DalVvTkFSbEMwbnZnMDFzSHNINHYwcU95ODVmNGlPN2dqNzk4RVZwcjNNVE5BZmFPTTNtCitUZit6cDdLTG93WFk4SzFZdUpzMEFoUGwyMUNmM05BYVBKeHloeFMvNHE3K1dRVEZoYStMUnNDUUdVTnhobTMKNWVYQWNJWEFSWkV6eUtHYWtyQ2NISy9XaXBLZlVBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["persistentvolumeclaims"]
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
      - operations: [ "CREATE" ]
        apiGroups: [ "apps" ]
        apiVersions: [ "v1" ]
        resources: [ "statefulsets" ]
