apiVersion: v1
kind: ServiceAccount
metadata:
  name: middleware-admission-webhook-sa
  labels:
    app: middleware-admission-webhook

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: middleware-admission-webhook-cr
  labels:
    app: middleware-admission-webhook
rules:
- apiGroups:
  - ""
  resources:
  - pvc
  verbs:
  - "*"
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "*"
- apiGroups:
  - maintenance.middleware.hc.cn
  resources:
  - "*"
  verbs:
  - "*"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: middleware-admission-webhook-crb
  labels:
    app: middleware-admission-webhook
subjects:
- kind: ServiceAccount
  name: middleware-admission-webhook-sa
  namespace: middleware-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: middleware-admission-webhook-cr
