apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zeus-normal-user
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - redis.middleware.hc.cn
  resources:
  - redisclusters
  verbs:
  - get
  - list
- apiGroups:
  - acid.zalan.do
  resources:
  - postgresqls
  verbs:
  - get
  - list
- apiGroups:
  - mysql.middleware.harmonycloud.cn
  resources:
  - mysqlclusters
  verbs:
  - get
  - list
- apiGroups:
  - harmonycloud.cn
  resources:
  - middlewarebackups
  - middlewarebackupschedules
  - middlewarerestores
  - middlewarerestoreresults
  - middlewarebackupresults
  - middlewares
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - patch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  - prometheusrules
  verbs:
  - get
  - list