apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zeus-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create