{{- if  .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: {{ include "mysql.fullname" . }}
spec:
  groups:
  - name: mysql-exporter
    rules:
    - alert: MySQLExporterDown
      annotations:
        message: "MySQL Exporter is down. (Namespace: {{ .Release.Namespace }},  ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: up
        product: harmonycloud
        service: metrics
      expr: up{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'} == 0
      for: 5m
      labels:
        severity: warning
  - name: mysql-cluster
    rules:
    - alert: MySQLReplicationNotRunning
      annotations:
        message: "MySQL slave replication (IO or SQL) has been down for more than 5 minutes. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: mysql_slave_status_slave_io_running
        product: harmonycloud
        service: metrics
      expr: mysql_slave_status_slave_io_running{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'} == 0 or mysql_slave_status_slave_sql_running{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'}
        == 0
      for: 5m
      labels:
        severity: warning
    - alert: MySQLReplicationLag
      annotations:
        message: "MySQL slave replication has fallen behind and is not recovering, current_value={{ `{{ $value }}` }}. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: mysql_slave_lag_seconds
        product: harmonycloud
        service: metrics
      expr: (mysql_slave_lag_seconds{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'} > 30) and on(instance) (predict_linear(mysql_slave_lag_seconds{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'}[5m],
        60 * 2) > 0)
      for: 5m
      labels:
        severity: warning
    - alert: MySQLInnoDBLogWaits
      annotations:
        message: "MySQL innodb logs are waiting for disk at a rate of {{`{{$value}}`}} second. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: mysql_global_status_innodb_log_waits
        product: harmonycloud
        service: metrics
        summary: MySQL innodb log writes stalling
      expr: rate(mysql_global_status_innodb_log_waits{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'}[15m]) > 10
      labels:
        severity: warning
  - name: mysql-stats
    rules:
    - alert: MySQLInstanceDown
      annotations:
        message: "MySQL Instance is down. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: mysql_up
        product: harmonycloud
        service: metrics
      expr: mysql_up{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'} == 0 or kube_pod_container_status_running{container="mysql", namespace='{{ .Release.Namespace }}', pod=~"{{ include "mysql.fullname" . }}-[0-9]"} == 0
      for: 5m
      labels:
        severity: critical
    - alert: MySQLOpenFilesHigh
      annotations:
        message: 'MySQL Open files is high, Please consider increasing open_files_limit, current_value={{ `{{ printf "%.0f" $value }}` }}%. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})'
        metric: mysql_global_status_innodb_num_open_files
        product: harmonycloud
        service: metrics
      expr: mysql_global_status_innodb_num_open_files{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'} * 100 / (mysql_global_variables_open_files_limit{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'}) > 75
      for: 5m
      labels:
        severity: warning
    - alert: MySQLReadBufferOutOfMaxAllow
      annotations:
        message: "MySQl read buffer size (read_buffer_size) is bigger than max. allowed packet size (max_allowed_packet).This can break your replication. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: mysql_global_variables_read_buffer_size
        product: harmonycloud
        service: metrics
      expr: mysql_global_variables_read_buffer_size{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'} > mysql_global_variables_slave_max_allowed_packet{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'}
      for: 5m
      labels:
        severity: warning
    - alert: MySQLTooManyConnections
      annotations:
        alertLevel: warning
        message: 'MySQL instance used more than 80% of max connections limited, current_value={{ `{{ printf "%.0f" $value }}` }}%. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})'
        metric: mysql_global_status_max_used_connections
        product: harmonycloud
        service: metrics
      expr: mysql_global_status_max_used_connections{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'} * 100/ mysql_global_variables_max_connections{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'} > 80
      for: 5m
      labels:
        severity: warning
    - alert: MySQLIOThreadStopped
      annotations:
        message: "MySQL instance IO thread has stopped. This is usually because it cannot connect to the Master any more. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: mysql_slave_status_slave_io_running
        product: harmonycloud
        service: metrics
      expr: mysql_slave_status_slave_io_running{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'} != 1
      for: 5m
      labels:
        severity: critical
    - alert: MySQLSQLThreadStopped
      annotations:
        message: "MySQL instance SQL thread has stopped. This is usually because it cannot apply a SQL statement received from the master. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: mysql_slave_status_slave_sql_running
        product: harmonycloud
        service: metrics
      expr: mysql_slave_status_slave_sql_running{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'} == 0
      for: 5m
      labels:
        severity: critical
    - alert: MySQLSQLThreadError
      annotations:
        message: "MySQL instance SQL thread has stopped. This is usually because it cannot apply a SQL statement received from the master. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: mysql_slave_status_slave_sql_running
        product: harmonycloud
        service: metrics
      expr: mysql_slave_status_slave_sql_running{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'} != 1
      for: 5m
      labels:
        severity: critical
    - alert: MySQLSlaveLaggingBehindMaster
      annotations:
        message: "MySQL instance Slave is lagging behind Master. Please check if Slave threads are running and if there are some performance issues, current_value={{ `{{ $value }}` }}. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: mysql_slave_status_seconds_behind_master
        product: harmonycloud
        service: metrics
      expr: mysql_slave_status_seconds_behind_master{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'} > 30
      for: 5m
      labels:
        severity: warning
    - alert: MySQLVolumeUsage70
      expr:  (100 * kube_persistentvolumeclaim_info{namespace='{{ .Release.Namespace }}', persistentvolumeclaim=~"mysql-data-{{ include "mysql.fullname" . }}-[0-9]"}) * on(volumename) group_left max(label_replace ((used_size_kb / total_size_kb),"volumename", "$1", "pv", "(.+)")) by (volumename) > 70
      for: 5m
      labels:
        severity: warning
      annotations:
        product: harmonycloud
        message: 'The disk usage of MySQL has exceeded 70%, current_value={{ `{{ printf "%.0f" $value }}` }}%.  (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Persistentvolumeclaim: {{`{{ $labels.persistentvolumeclaim }}`}})'

    - alert: MySQLVolumeUsage85
      expr: (100 * kube_persistentvolumeclaim_info{namespace='{{ .Release.Namespace }}', persistentvolumeclaim=~"mysql-data-{{ include "mysql.fullname" . }}-[0-9]"}) * on(volumename) group_left max(label_replace ((used_size_kb / total_size_kb),"volumename", "$1", "pv", "(.+)")) by (volumename) > 85
      for: 5m
      labels:
        severity: critical
      annotations:
        product: harmonycloud
        message: 'The disk usage of MySQL has exceeded 85%, current_value={{ `{{ printf "%.0f" $value }}` }}%.  (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Persistentvolumeclaim: {{`{{ $labels.persistentvolumeclaim }}`}})'

    - alert: MySQLFailOver
      annotations:
        message: 'The MySQL instance occurs Master-slave switchover or failover. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}'
      expr: delta(mysql_global_variables_read_only{namespace='{{ .Release.Namespace }}',pod=~'{{ include "mysql.fullname" . }}-[0-9]'}[5m]) > 0
      for: 20s
      labels:
        severity: warning

    - alert: MySQLWorkingSetMemoryUsageHigh95
      annotations:
        message: 'The workingSet memory(include Active Pages in the File System Cache) usage of MySQL has exceeded 95%, current_value={{ `{{ printf "%.0f" $value }}` }}%.  (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})'
      expr: sum(container_memory_working_set_bytes{namespace='{{ .Release.Namespace }}',pod=~'{{ include "mysql.fullname" . }}-[0-9]',endpoint!="",container="mysql"}) by (pod) * 100 / sum(kube_pod_container_resource_requests{namespace='{{ .Release.Namespace }}',pod=~'{{ include "mysql.fullname" . }}-[0-9]',resource="memory",container="mysql"}) by (pod) > 95
      for: 5m
      labels:
        severity: warning

    - alert: MySQLRSSMemoryUsageHigh80
      annotations:
        message: 'The rss memory usage of MySQL has exceeded 80%, current_value={{ `{{ printf "%.0f" $value }}` }}%.  (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})'
      expr: sum(container_memory_rss{namespace='{{ .Release.Namespace }}',pod=~'{{ include "mysql.fullname" . }}-[0-9]',endpoint!="",container="mysql"}) by (pod) * 100 / sum(kube_pod_container_resource_requests{namespace='{{ .Release.Namespace }}',pod=~'{{ include "mysql.fullname" . }}-[0-9]',resource="memory",container="mysql"}) by (pod) > 80
      for: 5m
      labels:
        severity: warning

    - alert: MySQLCpuUsageHigh
      annotations:
        message: 'The cpu usage of MySQL has exceeded 90%, current_value={{ `{{ printf "%.0f" $value }}` }}%.  (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})'
      expr: sum(rate (container_cpu_usage_seconds_total{namespace='{{ .Release.Namespace }}',pod=~'{{ include "mysql.fullname" . }}-[0-9]',endpoint!="",container="mysql"}[5m]) ) by (pod) * 100 / sum(kube_pod_container_resource_requests{namespace='{{ .Release.Namespace }}',pod=~'{{ include "mysql.fullname" . }}-[0-9]',resource="cpu",container="mysql"}) by (pod)  > 90
      for: 5m
      labels:
        severity: warning



  {{- if .Values.proxy.enable }}
  - name: proxysql
    rules:
    - alert: ProxySqlInstanceDown
      annotations:
        message: "MySQL ProxySQL is down. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: up
        product: harmonycloud
        service: metrics
      expr: up{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}'}== 0 or kube_pod_container_status_running{container="proxysql", pod=~"{{ include "mysql.fullname" . }}-proxy.*"} == 0
      for: 5m
      labels:
        severity: warning
    - alert: ProxySqlConnectCheckErr
      annotations:
        message: "MySQL ProxySQL connect check err. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: up
        product: harmonycloud
        service: metrics
      expr: irate(proxysql_mysql_monitor_connect_check_total{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}', status="err"}[5m]) > 0
      for: 5m
      labels:
        severity: warning
    - alert: ProxySqlPinCheckErr
      annotations:
        message: "MySQL ProxySQL ping check err. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: up
        product: harmonycloud
        service: metrics
      expr: irate(proxysql_mysql_monitor_ping_check_total{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}',status="err"}[5m]) > 0
      for: 5m
      labels:
        severity: warning
    - alert: ProxySqlReadOnlyCheckErr
      annotations:
        message: "MySQL ProxySQL read only check err. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: up
        product: harmonycloud
        service: metrics
      expr: irate(proxysql_mysql_monitor_read_only_check_total{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}',status="err"}[5m]) > 0
      for: 5m
      labels:
        severity: warning
    - alert: ProxySqlReplicationLagCheckErr
      annotations:
        message: "MySQL ProxySQL replication lag check err. (Namespace: {{ .Release.Namespace }}, ServiceName: {{ .Release.Name }}, Pod: {{`{{ $labels.pod }}`}})"
        metric: up
        product: harmonycloud
        service: metrics
      expr: irate(proxysql_mysql_monitor_replication_lag_check_total{namespace='{{ .Release.Namespace }}', service='{{ include "mysql.fullname" . }}', status="err"}[5m]) >0
      for: 5m
      labels:
        severity: warning
{{- end }}
{{- end }}