apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-proxy-cm
  labels:
    app.kubernetes.io/name: {{ include "mysql.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ (tpl (.Files.Glob "resource/proxysql/*").AsConfig . ) | indent 2 }}