apiVersion: v1
data:
  ca.crt: test
  healthcheck-client.crt: test
  healthcheck-client.key: test
kind: Secret
metadata:
  name: etcd-certs
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
type: Opaque