apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zeus-helm
  name: zeus-helm
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: {{ .Values.global.storageClass }}