apiVersion: v1
kind: Service
metadata:
  name: zeus
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: zeus
  sessionAffinity: None
  type: ClusterIP