apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeus
  namespace: {{ .Values.global.namespace }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
 {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zeus
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zeus
subjects:
- kind: ServiceAccount
  name: zeus
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zeus
  namespace: {{ .Values.global.namespace }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create



