image:
  repository: harbor.middleware.com/middleware
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 2
    memory: 8Gi
  requests:
    cpu: 2
    memory: 8Gi
# 日志可选择输出到logstash 或者kafka
logging_output:
  # type: kafka
  type: logstash
  address: logstash.logging
runtime:
  #  type: docker or containerd
  type: containerd
  imageDockerTag: 0.9.7-filebeat-hc.7-docker
  imageContainerdTag: 0.9.7-filebeat-hc.12-containerd-middleware
pathSymlink: /host/var/lib/kubelet:/appl/cdb/data/data/kubelet
customVolumes:
  mountPath: /appl/cdb/data
  hostPath: /appl/cdb/data
