image:
  repository: harbor.middleware.com/middleware
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# 日志可选择输出到logstash 或者kafka
logging_output:
  # type: kafka
  type: logstash
  address: logstash.logging

runtime:
  #  type: docker or containerd
  type: docker
  imageDockerTag: 0.9.7-filebeat-hc.7-docker
  imageContainerdTag: 0e1111e4

pathSymlink: /host/var/lib/kubelet:/appl/cdb/data/data/kubelet

customVolumes: {}



