alertmanager:
  alertmanagerSpec:
    tolerations:
      - operator: Exists
        key: harm.cn/system
      - operator: Equal
        key: harm.cn/type
        value: active-active
  podAntiAffinity: "soft"

global:
  imagePullSecrets:
  - name: registrysecret

