replicas: 3

tolerations:
  - operator: Exists

nodeAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      preference:
        matchExpressions:
          - key: system
            operator: In
            values:
              - "true"

podAntiAffinityTopologKey: "zone"

#取值[hard|soft] hard:强制反亲和 soft:非强制反亲和
podAntiAffinity: "soft"

imagePullSecrets:
  - name: registrysecret






