FROM openjdk11-alpine3.11:hc

# install tools
RUN apk add curl --no-cache &&\
    apk add bash --no-cache &&\
    apk add net-tools --no-cache

# install docker-cli
#RUN mkdir -p /tmp/docker &&\
#    cd /tmp/docker &&\
#    curl -LO "https://download.docker.com/linux/static/stable/x86_64/docker-18.09.9.tgz" && \
#    tar -zxvf /tmp/docker/docker-18.09.9.tgz && \
#    cp /tmp/docker/docker/docker /usr/local/bin/docker &&\
#    chmod +x /usr/local/bin/docker &&\
#    rm -rf /tmp/docker

# install kubectl
RUN mkdir -p /tmp/kubectl &&\
    cd /tmp/kubectl &&\
    curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.17.2/bin/linux/amd64/kubectl" && \
    cp /tmp/kubectl/kubectl /usr/local/bin/kubectl && \
    chmod +x /usr/local/bin/kubectl && \
    rm -rf /tmp/kubectl

# install helm
RUN mkdir -p /tmp/helm &&\
    cd /tmp/helm &&\
    curl -LO https://get.helm.sh/helm-v3.4.2-linux-amd64.tar.gz &&\
    tar -zxvf helm-v3.4.2-linux-amd64.tar.gz && \
    cp /tmp/helm/linux-amd64/helm /usr/local/bin/helm && \
    chmod +x /usr/local/bin/helm &&\
    rm -rf /tmp/helm

CMD ["/bin/bash"]
