{
 "title": "ProxySQL Fleet Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(proxysql_active_transactions, namespace)"
   },
   {
    "name": "mc",
    "label": "Mysql cluster",
    "query": "query_result(kube_statefulset_labels{namespace=\"$namespace\", label_operatorname=\"mysql-operator\"})"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\", created_by_name=~\"$mc-proxy.*\"}, pod) "
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\", pod=\"$pod\"}, node)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage(%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$pod\", container=\"proxysql\"}[3m]) )  / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=\"$pod\", container=\"proxysql\"})  * 100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Memory Usage(%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\", container=\"proxysql\"}) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=\"$pod\", container=\"proxysql\"}) * 100",
     "legendFormat": "Mem"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[5m]))",
     "legendFormat": "Network Receive"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[5m]))",
     "legendFormat": "Network Transmit"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total Active Transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(proxysql_active_transactions{namespace=\"$namespace\",pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Frontend Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "proxysql_client_connections_connected{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Frontend Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "proxysql_client_connections_connected{namespace=\"$namespace\",pod=\"$pod\"}/proxysql_mysql_max_connections{namespace=\"$namespace\",pod=\"$pod\"}*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backend Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "proxysql_server_connections_connected{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connection Overview",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(proxysql_client_connections_connected{namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "Total Frontend Connections"
    },
    {
     "expr": "sum(proxysql_connpool_conns{namespace=\"$namespace\",pod=\"$pod\",status=\"used\"})",
     "legendFormat": "Total Backend Connections (in-use)"
    },
    {
     "expr": "sum(proxysql_connpool_conns{namespace=\"$namespace\",pod=\"$pod\",status=\"free\"})",
     "legendFormat": "Total Backend Connections (free)"
    }
   ]
  },
  {
   "title": "Frontend Connection Overview",
   "type": "graph",
   "gridPos": { "h": 13, "w": 17, "x": 7, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proxysql_client_connections_non_idle{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{instance}} (used)"
    },
    {
     "expr": "proxysql_client_connections_connected{namespace=\"$namespace\",pod=\"$pod\"}-proxysql_client_connections_non_idle{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{instance}} (idle)"
    }
   ]
  },
  {
   "title": "Backend Connection Overview",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(proxysql_connpool_conns{namespace=\"$namespace\",pod=\"$pod\",status=\"used\"}) by (exported_endpoint)",
     "legendFormat": "{{ exported_endpoint }} (used)"
    },
    {
     "expr": "sum(proxysql_connpool_conns{namespace=\"$namespace\",pod=\"$pod\",status=\"free\"}) by (exported_endpoint)",
     "legendFormat": "{{exported_endpoint}} (free)"
    }
   ]
  },
  { "title": "Send/Receive Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Total Send / Receive Rates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(proxysql_queries_frontends_bytes_total{namespace=\"$namespace\",pod=\"$pod\",traffic_flow=\"sent\"}[$__rate_interval]))",
     "legendFormat": "Frontend Send Rate"
    },
    {
     "expr": "sum(irate(proxysql_queries_frontends_bytes_total{traffic_flow=\"received\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Frontend Receive Rate"
    },
    {
     "expr": "sum(irate(proxysql_queries_backends_bytes_total{traffic_flow=\"sent\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Backend Send Rate"
    },
    {
     "expr": "sum(irate(proxysql_queries_backends_bytes_total{traffic_flow=\"received\",namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Backend Receive Rate"
    }
   ]
  },
  {
   "title": "Connection Pool Backend Throughput SENT (irate MB/s)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_connpool_data_bytes_total{namespace=\"$namespace\",pod=\"$pod\",traffic_flow=\"sent\"}[$__rate_interval])/(1024*1024)",
     "legendFormat": "HG{{hostgroup}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Connection Pool Backend Throughput RECV (irate MB/s)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_connpool_data_bytes_total{namespace=\"$namespace\",pod=\"$pod\",traffic_flow=\"recv\"}[$__rate_interval])/(1024*1024)",
     "legendFormat": "HG{{hostgroup}} {{exported_endpoint}}"
    }
   ]
  },
  { "title": "Command", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Command Statistics (irate com/s)",
   "type": "graph",
   "description": "Total number of client & server connections (created|delayed|aborted).",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "c/s" } },
   "yaxes": [
    { "format": "c/s" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_com_autocommit_total{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "com_autocommit"
    },
    {
     "expr": "irate(proxysql_com_autocommit_filtered_total{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "com_autocommit_filtered"
    },
    {
     "expr": "irate(proxysql_com_rollback_total{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "com_rollback"
    },
    {
     "expr": "irate(proxysql_com_rollback_total_filtered{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "com_rollback_filtered"
    },
    {
     "expr": "irate(proxysql_com_backend_set_names_total{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "com_backend_set_names"
    },
    {
     "expr": "irate(proxysql_com_backend_change_user_total{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "com_backend_change_user"
    },
    {
     "expr": "irate(proxysql_com_backend_init_db_total{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "com_backend_init_db"
    },
    {
     "expr": "irate(proxysql_com_commit_cnt_filtered_total{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "com_commit_filtered"
    },
    {
     "expr": "irate(proxysql_com_frontend_set_names_total{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "com_frontend_set_names"
    },
    {
     "expr": "irate(proxysql_com_frontend_use_db_total{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "com_frontend_use_db"
    },
    {
     "expr": "irate(proxysql_com_frontend_use_db_total{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "com_frontend_use_db"
    },
    {
     "expr": "irate(proxysql_com_commit_cnt_total{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "com_commit"
    },
    {
     "expr": "irate(proxysql_com_commit_cnt_filtered_totalotal{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "com_commit_filtered"
    },
    {
     "expr": "irate(proxysql_selects_for_update__autocommit0_total{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "com_select_for_update_to_autocommit_off"
    }
   ]
  },
  { "title": "Backend Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Monitoring Check Status Totals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(proxysql_mysql_monitor_connect_check_total{namespace=\"$namespace\",pod=\"$pod\",status=\"err\"}[$__rate_interval])",
     "legendFormat": "Connect Errors"
    },
    {
     "expr": "irate(proxysql_mysql_monitor_ping_check_total{namespace=\"$namespace\",pod=\"$pod\",status=\"err\"}[$__rate_interval])",
     "legendFormat": "Ping Errors"
    },
    {
     "expr": "irate(proxysql_mysql_monitor_ping_check_total{namespace=\"$namespace\",pod=\"$pod\",status=\"err\"}[$__rate_interval])",
     "legendFormat": "Read-Only Errors"
    },
    {
     "expr": "irate(proxysql_mysql_monitor_replication_lag_check_total{namespace=\"$namespace\",pod=\"$pod\",status=\"err\"}[$__rate_interval])",
     "legendFormat": "Replication Lag Errors"
    }
   ]
  }
 ]
}