apiVersion: v1
appVersion: v0.0.24-1.0.1
description: Use HostPath for persistent local storage with Kubernetes
home: https://github.com/rancher/local-path-provisioner
keywords:
- storage
- hostpath
kubeVersion: '>=1.12.0-r0'
name: local-path-provisioner
sources:
- https://github.com/rancher/local-path-provisioner.git
version: 1.0.3
