{
 "title": "Minio 监控",
 "description": "Minio Version: RELEASE.2020-01-16T22-40-29Z",
 "tags": [ "object-storage" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "10s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(minio_version_info, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "query_result(minio_version_info{namespace=\"$namespace\"})"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "query_result(minio_version_info{namespace=\"$namespace\",service=\"$service\"})"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Minio is a high performance distributed object storage server, designed for large-scale private cloud infrastructure. For more information, check out the docs.",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://min.io/resources/img/logo/MINIO_wordmark.png\" style=\"height: 55px;\"></img>"
   }
  },
  {
   "title": "集群已使用空间",
   "type": "singlestat",
   "description": "Total number of offline disks for current MinIO server instances",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(disk_storage_used{namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "Total number of offline disks for current MinIO server instances"
    }
   ]
  },
  {
   "title": "磁盘离线个数",
   "type": "graph",
   "description": "Number of total/offline disks for current MinIO server instances",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_disks_offline{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "Offline instance"
    },
    {
     "expr": "minio_disks_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "Total instance"
    }
   ]
  },
  {
   "title": "硬盘使用率(%)",
   "type": "graph",
   "description": "Storage space usage",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_storage_used{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"} / disk_storage_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"} * 100",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "集群总容量",
   "type": "singlestat",
   "description": "Total number of disks for current MinIO server instances",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(disk_storage_total{namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "Total number of disks for current MinIO server instances"
    }
   ]
  },
  {
   "title": "Memory Working Set Usage(%)",
   "type": "graph",
   "description": "The percentage of requested memory resources that are actually being used (memory working set bytes) by the Minio Pod.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\",endpoint!=\"\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$pod\",resource=\"memory\"}) by (pod) * 100",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "CPU 使用率(%)",
   "type": "graph",
   "description": "Total user and system CPU time spent in seconds",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$pod\",endpoint!=\"\",container!=\"\"}[5m]) ) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$pod\",resource=\"cpu\"}) by (pod)  * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "S3数据输入/输出(KB/s)",
   "type": "graph",
   "description": "Data received x transmited by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(s3_rx_bytes_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[$interval])",
     "legendFormat": "Received: "
    },
    {
     "expr": "rate(s3_tx_bytes_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[$interval])",
     "legendFormat": "Transmited:"
    }
   ]
  },
  {
   "title": "集群内部节点数据传输(B/s)",
   "type": "graph",
   "description": "Data sent by current Minio server instance",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(internode_tx_bytes_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[$interval])",
     "legendFormat": "传输字节数:"
    },
    {
     "expr": "rate(internode_rx_bytes_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[$interval])",
     "legendFormat": "接收字节数:"
    }
   ]
  },
  {
   "title": "S3接口当前总请求数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_requests_current{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "S3接口总错误请求数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_errors_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}) by (api)",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "sum(s3_requests_current{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "S3接口总请求",
   "type": "graph",
   "description": "Data received by current Minio server instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_requests_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "HTTP请求状态",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(promhttp_metric_handler_requests_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "S3接口延迟统计",
   "type": "graph",
   "description": "The current aggregate time spent servicing all HTTP requests  in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "s3_ttfb_seconds_sum{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "{{api}}"
    }
   ]
  }
 ]
}