image:
  logpilotRepository: 10.1.11.121:8443/middleware/log-pilot
  logstashRepository: 10.1.11.121:8443/k8s-deploy/logstash
  logpilotImageTag: 0.9.7-filebeat-hc.2
  logstashImageTag: "6.8.21"
  imagePullPolicy: "Always"


podAntiAffinityTopologKey: "zone"

#取值[hard|soft] hard:强制反亲和 soft:非强制反亲和
podAntiAffinity: "soft"

