annotations:
  owner: harmonycloud
  type: db
  version: 6.8,7.16
apiVersion: v2
appVersion: 6.8.22
dependencies:
- alias: elasticsearch-operator
  condition: elasticsearch-operator.enabled
  name: elasticsearch-operator
  repository: file://./charts/elasticsearch-operator
  version: 1.7.9-4
description: Elasticsearch by Harmonycloud
name: elasticsearch
type: application
version: 1.7.9-4
