global:
  repository: harbor.middleware.com/middleware
  crdGroup: harmonycloud
  middlewarebackup_controller:
    image: middlewarebackup-controller
    removeBinlog: "yes"
    tag: 76f61d8b
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 512Mi
    nodeSelector: {}
    job_creator:
      jobTolerations: harm.cn/type
      jobNamespace: ""
      jobServiceAccount: job-creator
      # jobSecondsAfterFinished: 60
      # jobActiveDeadlineSeconds: 86400
      image: backup-job-creator
      tag: v1.0.4
    common_path_backup:
      image: middleware-backup-operator
      tag: v1.0.6-common
    job_pgsql_backup:
      image: middleware-backup-operator
      tag: aed02372
    job_mysql_backup:
      image: middleware-backup-operator
      tag: 57-ac03749c
      mysql8tag: 80-ac03749c
  kubectl:
    installCRDs: true
    tag: 1.21
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}

podAntiAffinityTopologKey: "kubernetes.io/hostname"

#取值[hard|soft] hard:强制反亲和 soft:非强制反亲和
podAntiAffinity: "soft"
